org: blendautoltda
app: alura-quiz
service: aws-node-http-api-project
frameworkVersion: '3'

params:
  default:
    dbName: serverless-app
  dev:
    connectionString: mongodb://localhost:27017/${self:params.default.dbName}

provider:
  name: aws
  runtime: nodejs18.x
  environment:
    MONGODB_CONNECTIONSTRING: ${param:connectionString}
    MONGODB_DB_NAME: ${param:dbName}

functions:
  sendResponse:
    handler: api/handlers.sendResponse
    events:
      - httpApi:
          path: /api/results
          method: post
          request:
            schemas:
              application/json: ${file(./api/schemas/sendResponse.json)}
  getResult:
    handler: api/handlers.getResult
    events:
      - httpApi:
          path: /api/results/{id}
          method: get

plugins:
  - serverless-offline
