org: blendautoltda
app: alura-quiz
service: aws-node-http-api-project
frameworkVersion: '3'

params:
  default:
    dbName: serverless-app
  dev:
    connectionString: mongodb://localhost:27017/${self:params.default.dbName}
    salt: '41665232692270171661944315883919'
  prd:
    connectionString: mongodb+srv://admin:admin123@cluster0.bui6e.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0

provider:
  name: aws
  runtime: nodejs18.x
  environment:
    MONGODB_CONNECTIONSTRING: ${param:connectionString}
    MONGODB_DB_NAME: ${param:dbName}
    SALT: ${param:salt}
  region: eu-west-1

functions:
  sendResponse:
    handler: api/handlers.sendResponse
    events:
      - httpApi:
          path: /api/results
          method: post
          request:
            schemas:
              application/json: ${file(./api/schemas/sendResponse.json)}
  getResult:
    handler: api/handlers.getResult
    events:
      - httpApi:
          path: /api/results/{id}
          method: get

plugins:
  - serverless-offline
